## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "false"
canonifyURLs = "true"

# Local
# baseURL = "/"
# publishDir = "public"

# Remote (GitHub Pages)
baseURL = "https://abreu4.github.io/saiis/"
publishDir = "public"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]